name: CI/CD for Airflow DAGs

on:
  push:
    paths:
      - "airflow/HomePlus_dag.py"
      - "airflow/Oasis_dag.py"
      - "airflow/Posty_dag.py"
    branches:
      - main  # 원하는 브랜치로 설정 가능

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rsync  # rsync 설치 단계 추가
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Transfer DAG file to GCE
      env:
        GCE_IP: ${{ secrets.GCE_IP }}
        GCE_USER: ${{ secrets.GCE_USER }}
        GCE_SSH_PRIVATE_KEY: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${GCE_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${GCE_IP}" >> ~/.ssh/known_hosts
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./airflow/HomePlus_dag.py ${GCE_USER}@${GCE_IP}:/home/patturning2/airflow/dags/HomePlus_dag.py
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./airflow/Oasis_dag.py ${GCE_USER}@${GCE_IP}:/home/patturning2/airflow/dags/Oasis_dag.py
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./airflow/Posty_dag.py ${GCE_USER}@${GCE_IP}:/home/patturning2/airflow/dags/Posty_dag.py
         
