name: CI/CD for Airflow DAGs

on:
  push:
    paths:
      - "airflow/dag.py"
    branches:
      - main  # 원하는 브랜치로 설정 가능

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Transfer DAG file to GCE
      env:
        GCE_IP: ${{ secrets.GCE_IP }}
        GCE_USER: ${{ secrets.GCE_USER }}
        GCE_SSH_PRIVATE_KEY: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
      run: |
        echo "$GCE_SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o "StrictHostKeyChecking=no" airflow/dag.py ${GCE_USER}@${GCE_IP}:~/airflow/dags/
