# .github/workflows/ci-cd.yml
name: server CI/CD Pipeline

on:
  push:
    paths: 
      - "server/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.8'

      - name: Build with Gradle
        run: |
          cd server
          ./gradlew build -x test

      - name: Deliver jar File through Bastion Host
        if: success()
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.GCP_BASTION_HOST }}
          username: ${{ secrets.GCP_BASTION_USER }}
          key: ${{ secrets.GCP_BASTION_SSH_PRIVATE_KEY }}
          port: 22
          source: server/build/libs/swdc-0.0.1-SNAPSHOT.jar
          target: /home/patturning2/server/Dark-Pattern-Detection-SWDeveloperContest/deployment/

      - name: Remove unused images
        run: |
          sudo docker image prune -f

      - name: Deploy to Internal Server through Bastion Host
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i <(echo "${{ secrets.GCP_BASTION_SSH_PRIVATE_KEY }}") \
            -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i <(echo '${{ secrets.GCP_BASTION_SSH_PRIVATE_KEY }}') ${{ secrets.GCP_BASTION_USER }}@${{ secrets.GCP_BASTION_HOST }}" \
            ${{ secrets.GCP_INTERNAL_SERVER_USER }}@${{ secrets.GCP_INTERNAL_SERVER_VM_HOST }} << EOF
              sudo docker stop swdc-container || true
              sudo docker rm swdc-container || true

              cd /home/patturning2/server/Dark-Pattern-Detection-SWDeveloperContest/deployment
              sudo docker build -t swdc-app .
              sudo docker run -d -p 8080:8080 --name swdc-container -v /mnt:/mnt swdc-app
            EOF
