# .github/workflows/ci-cd.yml
name: server CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: '8.8'

    - name: Build with Gradle
      run: |
        cd server
        ./gradlew build -x test
      
    - name: Deploy
      if: success()  
      run: echo "Deploy your application here"
